### ISSUE TITLE
model cannot download now

### ISSUE THREAD

**Issue by KevenLee** [youngwanLEE/VoVNet-RefineDet#1]
Thanks for your jobs. I cannot download VoVNet39-RefineDet512 model now. Could you help me. Thanks

**Comment by stigma0617** [comment]
@KevenLee 
It is because the Dropbox policy was changed. I modified the urls.

**Comment by youngwanLEE** [comment]
@KevenLee 

It is because the Dropbox's policy was changed. 

I modified the urls. check again :)
