### ISSUE TITLE
./data/VOC0712/create_list.sh: 허가 거부

### ISSUE THREAD

**Issue by seunghoSHIN92** [youngwanLEE/VoVNet-RefineDet#4]
빌드를 완료하고 prerparation을 진행하는 중에 2번에서 진행이 안되는 현상이 발생했습니다.
README.md의 2번에 있는 ./data/VOC0712/create_list/sh를 입력하고 실행하였는데 허가거부라고 뜨면서 진행이 안됩니다. 관리자모드로 변경해서 진행하여도 여전히 허가거부라고 뜹니다. 어떻게 하면 될까요?
컴퓨터 사양은 우분투 16.04, Nvidia Geforce 970, CUDA 8.0, cuDNN 7.0.5입니다.

**Comment by youngwanLEE** [comment]
@seunghoSHIN92 
Please ask in English for other people.

Your problem is not related to this repo. 

I think your problem may be wrong path or file (or directory) authorization.
